### ISSUE TITLE
Re-ordering columns in Select

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#233]
Two scenarios I've come across.

1. I select all columns and then remove the ones I don't need. I would then like to change the order.
2. I manually select some columns, but then want to INSERT another column (not append it to the end)

**Comment by k8hughes** [comment]
I'll add this one to the backlog - once work on existing features has been delivered we can assess how much work it would take to do this and do a cost vs benifit analysis.

**Comment by edwinmp** [comment]
NB: https://github.com/clauderic/react-sortable-hoc

**Comment by edwinmp** [comment]
@ThatcherK  We shall use the [DND Kit](https://github.com/clauderic/dnd-kit) for this.

I want to keep the alphabetical checkbox selector since it makes finding specific columns a lot easier in a large list. Sadly, I don't think it's the ideal structure for drag/drop behaviour.
So we're going to have **two** views; one for selecting & one for ordering.

1. Add a switch/checkbox for toggling between the two states. When selecting (default), the label is `Order Columns`, which on click changes to `Select Columns`.
2. When the active view is for selecting, the `Select All` & `Deselect All` buttons are visible. They're hidden when ordering.
3. The entire checkbox select view is hidden when ordering
4. Create a suitable view based around the dnd-kit that allows one to rearrange a list of **selected** columns by dragging & dropping them to the desired position. I don't mind if it's not perfectly styled in the beginning as long as it behaves as expected. Ask for a review at this point.
5. Naturally, the view in 4 is only visible when ordering
6. This behaviour must persist on save i.e. the user's column order should be retained on save and visible on edit, but the select view must remain alphabetical.

**Comment by ThatcherK** [comment]
So does this mean that once a user selects the required columns,if they so need them ordered in a particular way,they can click the toggle button to change to the order columns view,if not they simply save as usual?

**Comment by edwinmp** [comment]
> So does this mean that once a user selects the required columns,if they so need them ordered in a particular way,they can click the toggle button to change to the order columns view,if not they simply save as usual?

That's right. Unless manually updated, the ordering will remain alphabetical.

**Comment by k8hughes** [comment]
@edwinmp is this on staging for someone to test?

**Comment by edwinmp** [comment]
It's on staging and ready for review

We added a button on the Select step for ordering columns

![image](https://user-images.githubusercontent.com/5672438/116057542-92493880-a687-11eb-9a57-2bf358c641c6.png)

It switches to a view of the selected columns. Drag & drop a column to the position you want it.

![image](https://user-images.githubusercontent.com/5672438/116057751-c9b7e500-a687-11eb-9a6b-63a17b3b6b8d.png)

Preview or save and preview to see the ordering take effect

**Comment by k8hughes** [comment]
@dean-breed would you have time to test this on staging and see if it works ok?

**Comment by dean-breed** [comment]
@edwinmp @k8hughes If I have a list longer than the screen and I move one from the bottom up, when the screen auto scrolls, the title I'm holding stays low (doesn't stick on the mouse). There is no auto scroll down which means I can't move anything to the bottom of the list easily.

**Comment by edwinmp** [comment]
@k8hughes I'll be making an update on this today ... thinking of eliminating the need to scroll entirely & maybe numbering the items.
