### ISSUE TITLE
Save metadata

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#25]
Update, edit meta data

**Comment by akmiller01** [comment]
CRUD metadata is possible with https://github.com/devinit/ddw-analyst-ui/pull/59

**Comment by akmiller01** [comment]
Clarification on this one needed @Napho and @edwinmp . Do we want users to Save metadata? Or Admins? I've made the endpoints so admins can update metadata, but we'd need to make fewer fields read_only for users to do so through the API.

**Comment by edwinmp** [comment]
This is where I prefer permissions to roles. Wouldn't want to give someone admin access just because they're most qualified to update CRS metadata. That'd give them access to all admin features. Would be nice to just give a user `write` permissions to the metadata model.
This would also eliminate having a single/few admin users who keep getting bothered with requests to add this and update that.

**Comment by k8hughes** [comment]
I thought we'd discussed having:
 `super admin`  - developer level access
`admin` - Duncan or other trained analysts
`analyst user` - everyone else

Is this still the plan?

**Comment by akmiller01** [comment]
We can still have permissions to that effect, but the question I was trying to ask is:

Does Edwin need to build a front-end interface to the metadata? Or are we happy with giving `/admin` panel access to anyone who would ever need to change the metadata (and restricting their permissions to allow them to write metadata, but not do things like add or remove users).

**Comment by akmiller01** [comment]
As discussed, this issue is somewhat out of scope for MVP since metadata will be created by devs and not maintained by users.
