### ISSUE TITLE
Data Sources: Updated On date

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#253]
These dates suggest that everything in DDW has been updated in the last week. Is this correct??

![DDW Source update](https://user-images.githubusercontent.com/3491562/88646617-2799ab00-d0bd-11ea-845d-901888b05573.png)

**Comment by akmiller01** [comment]
Yes, it's correct, but it's a bit naive. We've got this convenience function for updating meta data to flag when a dataset is updated: https://github.com/devinit/ddw-analyst-ui/blob/develop/data/management/commands/update_meta.py

For all of those sources flagged as being updated Friday, that's because I did a re-import of the manual metadata CSVs which updates all static data sources. It's not checking which ones in particular have changed (we're not storing hashes), they're just dropped and rebuilt.

**Comment by bill-anderson** [comment]
So the meaning is "it was up to date when checked on this date - irrespective of whether it changed or not". That is valid ...
