### ISSUE TITLE
IATI Transactions: Analysis of number of rows per activity

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#321]
Could we run the following counts. Two tables with the following columns

1. Publisher | Number of activities | Average rows per activity
2. Rows per activity | Number of activities (with that number of rows)

(Is there a reason that the UI doesn't have a count option on Aggregate?)

**Comment by akmiller01** [comment]
I think we had considered adding COUNT, but concluded it wouldn't be used by analysts. There's no reason we couldn't add it to aggregate.

I'm still waiting on this PR to be reviewed and merged, which will increase row counts slightly: https://github.com/devinit/ddw-analyst-ui/pull/319 There's currently a bug where if the sector data comes from the transaction level, only the first sector is recorded (because all transaction sectors are 100%), and this PR fixes this and allows the data to pick up all transaction-level sectors.

But in the meantime here's the queries I put together for your questions and the data:

1. `select reporting_org_ref, count(distinct(iati_identifier)), cast(count(iati_identifier) AS DECIMAL)/count(distinct(iati_identifier)) from repo.iati_transactions group by reporting_org_ref;`

[iati_ref_table.zip](https://github.com/devinit/ddw-analyst-ui/files/5203443/iati_ref_table.zip)

2. `select "sq1".row_count, count("sq1".iati_identifier) from (select iati_identifier, count(x_transaction_number) as row_count from repo.iati_transactions group by iati_identifier) AS sq1 group by row_count;`

[iati_row_table.zip](https://github.com/devinit/ddw-analyst-ui/files/5203446/iati_row_table.zip)

**Comment by akmiller01** [comment]
And if you were as curious as me which activity had the 320,280 rows:

```
analyst_ui=# select iati_identifier from (select iati_identifier, count(x_transaction_number) as row_count from repo.iati_transactions group by iati_identifier) as sq1 where sq1.row_count=320280;
    iati_identifier    
-----------------------
 GB-CHC-1105851-AADC62
(1 row)
```

51 sectors x 6280 transactions...

**Comment by bill-anderson** [comment]
Thanks, very useful

Could you count number of rows:
Transaction_value_usd = 0 | Transaction_value_usd < 10 | transaction_value_usd < 100

**Comment by akmiller01** [comment]
There were more null valued rows than zero valued, so I included a null case too:

```
analyst_ui=# select sum(sq1.transaction_null), sum(sq1.transaction_zero), sum(sq1.transaction_ten), sum(sq1.transaction_hundred) from (select case when x_transaction_value_usd is null then 1 else 0 end as transaction_null, case when x_transaction_value_usd = 0 then 1 else 0 end as transaction_zero, case when x_transaction_value_usd < 10 then 1 else 0 end as transaction_ten, case when x_transaction_value_usd < 100 then 1 else 0 end as transaction_hundred from repo.iati_transactions) as sq1;
  sum   | sum |   sum   |   sum   
--------+-----+---------+---------
 990443 |   0 | 2641116 | 3590637
(1 row)
```

**Comment by bill-anderson** [comment]
So currently out of approx 18m rows in total, 1m (5%) are 0 valued and 2.5m (15%)  are <$10

Ditching rows in terms of insignificance (we are pragmatic analysts not auditors) doesn't look to be worth it. Dropping 15% of the database is hardly going to lead to a major change in performance.

**Comment by akmiller01** [comment]
Also doing a quick audit of which currency/year combinations are causing null valued x_transaction_value_usd results when x_transaction_value is not null. Seems like mostly old/incorrect years or odd currencies:
```
analyst_ui=# select distinct(x_currency, x_transaction_year) from repo.iati_transactions where x_transaction_value is not null and x_transaction_year is not null and x_transaction_value_usd is null and x_transaction_value > 0;
    row     
------------
 (DKK,1970)
 (ETB,1970)
 (EUR,1902)
 (EUR,1914)
 (EUR,1970)
 (EUR,2030)
 (EUR,2081)
 (EUR,2106)
 (EUR,2108)
 (GBP,1970)
 (GBP,2025)
 (GBP,2026)
 (GBP,2027)
 (GBP,2028)
 (GBP,2029)
 (GBP,2030)
 (GBP,2107)
 (PKR,2020)
 (USD,201)
 (USD,1970)
 (USD,1976)
 (USD,1977)
 (USD,1978)
 (USD,1979)
 (VND,2017)
 (VND,2018)
 (VND,2019)
 (XDR,1967)
...
```
