### ISSUE TITLE
Scheduled event log not showing duration

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#458]
Since 18 Feb the start time and end time of the IATI refresh is the same. Is this a problem with the log display, or has the refresh failed?

![ddw event log](https://user-images.githubusercontent.com/3491562/109655569-55673680-7b5b-11eb-96d0-b7b49e91c1f1.png)

**Comment by k8hughes** [comment]
Hmmmm I know that a fix was deployed to make sure the time was not shifting later, so maybe some sort of bug as been introducted.  I'll ask the team to verify that the data is updating as a matter of urgency.  Once we know the answer to that we can make a prioritisation for this issue.

**Comment by edwinmp** [comment]
@bill-anderson David noticed that a while back and after investigating, we concluded that this appears to be the case because the IATI updates are running in under a minute. Other scheduled events appear fine & are running the same code.
My assumption was that there isn't always new data on IATI, so the updates are quick. Am I wrong? @akmiller01 
Still, it's strange given the average time of past events was a lot longer for IATI.

**Comment by bill-anderson** [comment]
This can't be correct. No new upates from 18 Feb until now is not possible.
UK FCDO updated at about 05:00 this morning so it is important that we see this in the morning

**Comment by wakibi** [comment]
The other Scheduled events are running fine, this is an issue specific to IATI. For some reason it's not picking some environmental variables it needs to finalise the update

**Comment by edwinmp** [comment]
So @wakibi you're saying the update is failing but that failure isn't being picked up by the code? If you have it, could you share the stack trace so we can know what error to handle.

**Comment by wakibi** [comment]
Yes, that's correct. The trace from the `bash` script that actually does the updates?

**Comment by edwinmp** [comment]
The bash script runs a management command, so I'm sure there's a python stack trace somewhere if things are breaking ... if not, then it's being handled too well that the script doesn't return a failed error code, which explains why the scheduled event is not catching it. Bottom line, it needs to be handled somewhere, even if its by sending an email to all registered admins that vital env variables are missing.

**Comment by wakibi** [comment]
@edwinmp  not sure I actually gave the right response to your last question, but the said Environmental variables are needed by the `iati.sh` script to run the update. These have been previously copied over during the deployment process to the bash profile. The issue is with the new deployment process, it does not copy the environmental variables from the host server to the bash profile of the container. So yes, like you said, we need to handle it at the script that needs those Env variables. Here is the trace from the script in question;

```
Traceback (most recent call last):
  File "data_updates/Python/iati_transactions.py", line 38, in <module>
    raise(Exception('S3_KEY or S3_SECRET not found. Please configure environmental variables before continuing.'))
Exception: S3_KEY or S3_SECRET not found. Please configure environmental variables before continuing.
```

Cheers.

**Comment by edwinmp** [comment]
I'll handle the deployment issue, but we also need to take care of the fact that this fails silently. If you have the correct values for the variables, please set them so we can trigger the IATI update manually.
