### ISSUE TITLE
Advanced Query Builder - Joining a Second Dataset

### ISSUE THREAD

**Issue by JennyR-DI** [devinit/ddw-analyst-ui#583]
I’ve been trying to LEFT JOIN the ‘DAC2B ISO codes’ dataset to the data source ‘OECD DAC2B: OOFs and export credits’, but I haven’t been able to get it to work out.   Can you please advise the best way to add a JOIN in the advanced query?

I’ve tried mapping ‘Donor Name’ to ‘Country Name’ and also ‘Donor Code’ to ‘Country Code’, in an attempt to add a column containing ISO codes from the the ‘DAC2B ISO codes’ dataset.

I got the following error for my latest attempt:
![image](https://user-images.githubusercontent.com/90774534/134209180-273ac649-f11d-4807-86b8-a4d7269d10c4.png)

**Comment by wakibi** [comment]
@edwinmp this seems to be a user issue. Do we have new end user documentation with Advanced QB included?

**Comment by JennyR-DI** [comment]
Thanks Chris for your help, I just wanted to confirm that the JOIN worked for me after I selected the columns from the new data source.

**Comment by wakibi** [comment]
@JennyR-DI apologies as we have not yet come up with documentation for this, we shall update our Docs. Cheers.

**Comment by edwinmp** [comment]
Hi @JennyR-DI thanks so much for the extensive testing. There is basic documentation for all the actions [here](https://docs.google.com/document/d/1nB9wzBQ-TTFn1k3pssEweNxKhDv1JoFfgvLVYijAz1I/edit#heading=h.hs41pqvjpw22) ... since the feature is in beta, we didn't want to spend a lot of time documenting features we're likely to change. If it'll help (especially with the filters), I can schedule a chat and take you through it.

As for the issue above, I reviewed the error emails and the data source you were trying to join with somehow isn't valid (supposedly doesn't exist). This is why attempting with a different source didn't result in the same error.

**Comment by edwinmp** [comment]
@JennyR-DI Do you recall the sources you were attempting to join? It'd be great if we could replicate the problem and work on a proper fix regardless of the cause.

**Comment by edwinmp** [comment]
Ah, seen them in the original ticket ... never mind :)

**Comment by JennyR-DI** [comment]
Thanks Edwin for looking into this issue and for sending that document it looks really helpful.

**Comment by edwinmp** [comment]
Closed in favour of ticket https://github.com/devinit/ddw-analyst-ui/issues/591 for multiple joins
