### ISSUE TITLE
"deflate" via a "join" to deflator table

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#65]
Should this be a division via a table or something in the code?

**Comment by akmiller01** [comment]
@Duncan-Knox we talked about this just being a "join" of a deflator table rather than a pre-configured deflate command. Thoughts?

**Comment by Duncan-Knox** [comment]
@akmiller01 my thoughts are still in support of deflation being used through a join in the initial phase. This is because there's more than one deflator set (e.g. different price bases in US$ and PPP$) and the OECD data comes with 'ready-deflated' options, which might limit the need for a lot of deflation. Other data, such as international resource flows, will be submitted having been deflated already. I'd argue it could be worth testing the extent to which a deflate option is supported by analysts from regular use of the interface before considering building it in for the next phase. How does this sounds to you?

**Comment by k8hughes** [comment]
I will mark this as blocked for now, so we can decide at a later date if we need it or not.

**Comment by k8hughes** [comment]
@Duncan-Knox what are you thoughts on the relvance of this issue given where we are today?

**Comment by Duncan-Knox** [comment]
I think it would be more towards the 'luxury' side of the scale rather than the necessity side in terms of where we are today. It may take a while to get up and running and it would probably require a fair amount of maintenance time. One day maybe...
For now I'd still support deflate through join. Can see why a command would be popular but there are practicalities to consider.

**Comment by k8hughes** [comment]
I'll change the issue title to having a deflator table as that sounds worth while.
@Duncan-Knox does such a table exist?

**Comment by Duncan-Knox** [comment]
Sure @k8hughes this exists. Its on the DDW though for 2016 and 2017 only, we ought to add a 2018 set and by May a 2019 set.

**Comment by k8hughes** [comment]
Can you get the data for 2018 and 19 and attach it to this issue?  Then we can update the table

**Comment by Duncan-Knox** [comment]
Here are the 2018 deflators. I think its best to wait until April to do the 2019 ones with the new OECD data.

[DI deflators constant 2018 USD.xlsx](https://github.com/devinit/ddw-analyst-ui/files/6001814/DI.deflators.constant.2018.USD.xlsx)

**Comment by k8hughes** [comment]
@wakibi or @akmiller01 would one of you be able to do this data update?
@Duncan-Knox  thanks so much

**Comment by edwinmp** [comment]
@wakibi was this data update done?

**Comment by akmiller01** [comment]
https://github.com/devinit/ddw-data-update-configs/pull/5

**Comment by akmiller01** [comment]
Worth keeping this issue open for the 2019 deflators?
